---
- name: Create cron entries
  cron:
    name: "{{ item.name }}"
    user: "{{ item.user }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    day: "{{ item.day }}"
    weekday: "{{ item.weekday }}"
    month: "{{ item.month }}"
    state: present
  with_items: cron_jobs
  register: jobs

- debug:
    var: jobs
