---
- set_fact:
    docker_env: "{{ base_docker_env }}"
  when: docker_env is undefined

- block:
  - set_fact:
      needed_container_state: exited

  - include: actions/deploy_docker.yml

  - set_fact:
      needed_container_state: running

  - include: actions/deploy_docker.yml

  when: initialize is undefined

- block:
  - pause: seconds=2
  - name: "Get status endpoint for http://{{ inventory_hostname }}:{{ status_port }}{{ status_path }}"
    local_action:
      module: uri
      method: GET
      url: "http://{{ inventory_hostname }}:{{ status_port }}{{ status_path }}"
      return_content: yes
    register: service_status
    until: service_status.status == 200
    retries: 18
    delay: 10

  - debug:
      var: service_status

  - fail:
      msg: "Status is not ok for http://{{ inventory_hostname }}:{{ status_port }}{{ status_path }}"
    when: service_status.json['status'] != 'ok'

  - fail:
      msg: "Docker Tag {{ docker_tag }} does not match {{ service_status.json['commit'] }}"
    when: service_status.json['commit'] | search(fail_when_not_match)

  when: initialize is undefined and asg_health_check_type == "ELB"
