---
- block:
  - set_fact:
      aws_sg:
        group_id: "{{ office_sg_ids }}"
      aws_base_ami: "{{ aws_base_ami_name | latest_ami_id(aws_region) }}"
      vpc_subnet_id: "{{ aws_vpc_id |get_subnet_ids([aws_public_cidrs.a], aws_region) |first  }}"
      ssh_user: ansible
      
  - include: resources/iam_role.yml
  - include: resources/iam_policy.yml
  - include_vars: instance_profile.yml
  - include: resources/ec2.yml
  - include: resources/add_host.yml

  when: aws_vpc_name == mgmt_vpc_name and asg_deploy is undefined

- block:
  - set_fact:
      aws_sg:
        group_id: "{{ office_sg_ids }}"
      aws_base_ami_name: "{{ service }}-*"
      dont_include: no
      combined_rules: "{{ app_rules_mgmt_sg + mgmt_ssh_rules }}"
  - include: common.yml
  when: aws_vpc_name  == mgmt_vpc_name and asg_deploy is defined
