---
- block:
  - name: "Launch {{ service  }} container"
    docker: 
      name: "{{ service }}"
      image: "{{ docker_image }}:{{ docker_tag }}"
      ports: "{{ docker_ports |default(omit) }}"
      expose: "{{ docker_expose_ports |default(omit) }}"
      env: "{{ docker_env }}"
      restart_policy: "{{ docker_restart_policy }}"
      volumes: "{{ docker_volumes }}"
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      hostname: "{{ inventory_hostname }}"
    register: launch_container and initialize is undefined
  - debug:
      var: launch_container
  when: needed_container_state == 'running'

- block:
  - name: "Destroy {{ service }} container"
    docker: 
      name: "{{ service }}"
      image: "{{ docker_image }}:{{ docker_tag }}"
      state: absent
    register: destroy_container
  - debug:
      var: destroy_container
  when: needed_container_state != 'running' and initialize is undefined
