---
- block:
  - name: Initialize Database Tables
    docker:
      name: "initialize_{{ service }}-{{ env }}"
      command: "{{ create_table_command }}"
      image: "{{ docker_image }}:develop"
      ports: "{{ app_ports|dockered_port_join }}"
      expose: "{{ app_ports|join(',') }}"
      env: "{{ docker_env }}"
      pull: always
      volumes: "{{ docker_volumes }}"
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      hostname: "{{ inventory_hostname }}"
  when: needed_container_state == 'running'

- block:
  - name: "Destroy container"
    docker: 
      name: "initialize_{{ service }}-{{ env }}"
      image: "{{ docker_image }}:develop"
      state: absent
    register: destroy_container
  when: needed_container_state != 'running'
