---
- block:
  - name: Login to Docker Hub
    shell: docker login -e {{docker_hub_email}} -u {{docker_hub_username}} -p {{docker_hub_password}}
    no_log: True

  - name: Pull Docker Image
    shell: docker pull {{ docker_image }}:develop
    no_log: True

  - name: Initialize API Keys
    docker: 
      name: "{{ item.key }}"
      command: '{{ create_keys_command }} -desc "{{ item.value.desc }}" -scopemask "{{ item.value.scope }}" -token "{{ item.value.token }}"'
      image: "{{ docker_image }}:develop"
      ports: "{{ app_ports|dockered_port_join }}"
      expose: "{{ app_ports|join(',') }}"
      env: "{{ docker_env }}"
      volumes: "{{ docker_volumes }}"
    with_dict: "{{ tokens }}"
  when: needed_container_state == 'running' and initialize is defined

- block:
  - name: "Destroy container"
    docker: 
      name: "{{ item.key }}"
      image: "{{ docker_image }}:develop"
      state: absent
    with_dict: "{{ tokens }}"
  when: needed_container_state != 'running' and initialize is defined
