---
zones: "{{ aws_region | zones() }}"
aws_vpc_id: "{{ aws_vpc_name | get_vpc_id_by_name(aws_region) }}"
aws_mgmt_vpc_id: "{{ mgmt_vpc_name | get_vpc_id_by_name(aws_region) }}"

aws_private_subnets: "{{ aws_vpc_id | get_subnet_ids(aws_private_cidrs.values(), aws_region)  }}"
aws_public_subnets: "{{ aws_vpc_id | get_subnet_ids(aws_public_cidrs.values(), aws_region)  }}"
aws_persistent_subnets: "{{ aws_vpc_id | get_subnet_ids(aws_persistent_cidrs.values(), aws_region)  }}"

mgmt_sg_name: "{{ mgmt_vpc_name }}-Public"

mgmt_global_sg_id: "{{ mgmt_sg_name |get_sg(aws_mgmt_vpc_id, aws_region) }}"
mgmt_public_cidrs: "{{ mgmt_sg_name |get_sg_cidrs(aws_mgmt_vpc_id, aws_region) }}"

env_global_private_sg_id: "{{ aws_private_subnet_name |get_sg(aws_vpc_id, aws_region) }}"
env_global_public_sg_id: "{{ aws_public_subnet_name |get_sg(aws_vpc_id, aws_region) }}"
env_global_persistent_sg_id: "{{ aws_persistent_subnet_name |get_sg(aws_vpc_id, aws_region) }}"
