---
- include: resources/vpc.yml
- include: resources/igw.yml
- pause: seconds=5
- include: resources/route53.yml
- include: resources/subnets.yml
- pause: seconds=5
- include: resources/security_groups.yml
- pause: seconds=5
- include: resources/nat.yml
- pause: seconds=5
- include: resources/routes.yml
- pause: seconds=5

- set_fact:
    vpc_id: "{{ mgmt_vpc_name | vpc_exists(aws_region) }}"
    
- block:
  - block:
    - set_fact:
        all_vpcs_except_mgmt: "{{[vpc_id] | get_all_vpcs_info_except() }}"
        routes_except_mgmt: "{{ vpc_id | get_all_route_table_ids_except(aws_region) }}"
        mgmt_routes: "{{ vpc_id | get_route_table_ids(aws_region) }}"
        vpc_name: "{{ mgmt_vpc_name }}"

    - include: resources/peering.yml
    when: '"{{ vpc_id }}" != "does not exist" and "{{ aws_vpc_name  }}" | search("!management", ignorecase=True)'
  when: '"{{ aws_vpc_name }}" | search("!management", ignorecase=True)'
