- hosts: all

  pre_tasks:
    - name: Check for required vars
      fail:
        msg: "This play requires a variable named {{ item }}"
      when: "{{ item }} is not defined"
      with_items:
        - service
        - env

  tasks:
    - include_vars: "group_vars/services/{{ service }}.yml"
    - include_vars: "group_vars/environments/{{ env }}/network.yml"
    - include_vars: "group_vars/environments/{{ env }}/services/{{ service }}.yml"

  post_tasks:
    - set_fact:
        search_tags:
          service: "{{ service }}"
          env: "{{ env }}"

    - name: Add tagged hosts to groups
      add_host:
        name: "{{ item }}"
        groups: "{{ service }}-{{ env }}-ec2"
        ansible_connection: ssh
        ansible_user: ubuntu
      with_items: "{{ aws_region | get_instances_by_tags(search_tags, state='running') }}"
      register: tagged_nodes

    - debug:
        var: tagged_nodes
